"""SQLite-backed queue of batch tutor corrections awaiting human review.

Entirely additive and independent from agent.pending_correction /
agent.approve_correction() / agent.reject_correction() in brain/agent.py --
those still own the single live-chat correction slot exactly as before. This
is a second, separate review queue for corrections generated in bulk by the
background worker in interfaz/web_mind.py, so a batch of tutor calls can run
unattended and a human reviews the results afterward, without ever touching
the live single-correction flow.

Persisted (not in-memory) so a backlog of already-generated -- i.e. already
Groq-API-spent -- corrections survives a web_mind.py restart.
"""

from __future__ import annotations

import json
import sqlite3
import time
from pathlib import Path
from typing import Any

VALID_STATUSES = ("pending", "approved", "rejected")


class CorrectionQueue:
    """Stores tutor corrections generated by the batch worker, one row per
    question processed, until a human approves/rejects/edits them."""

    def __init__(self, database_path: str | Path) -> None:
        self.database_path = Path(database_path)
        self.connection = sqlite3.connect(self.database_path, check_same_thread=False)
        self.connection.row_factory = sqlite3.Row
        self.connection.execute(
            """
            CREATE TABLE IF NOT EXISTS correction_queue (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                question TEXT NOT NULL,
                raw_answer TEXT NOT NULL,
                corrected_answer TEXT,
                new_words TEXT NOT NULL DEFAULT '[]',
                created_at REAL NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending'
            )
            """
        )
        self.connection.commit()

    def enqueue_result(
        self,
        question: str,
        raw_answer: str,
        corrected_answer: str | None,
        new_words: list[str],
        status: str = "pending",
    ) -> int:
        if status not in VALID_STATUSES:
            raise ValueError(f"status must be one of {VALID_STATUSES}, got {status!r}")
        cursor = self.connection.execute(
            """
            INSERT INTO correction_queue
                (question, raw_answer, corrected_answer, new_words, created_at, status)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (question, raw_answer, corrected_answer, json.dumps(new_words), time.time(), status),
        )
        self.connection.commit()
        return int(cursor.lastrowid)

    def get(self, entry_id: int) -> dict[str, Any] | None:
        row = self.connection.execute(
            "SELECT * FROM correction_queue WHERE id = ?", (entry_id,)
        ).fetchone()
        return self._row_to_dict(row) if row else None

    def pending(self, limit: int = 20) -> list[dict[str, Any]]:
        """Up to `limit` entries with status='pending' -- i.e. the tutor
        produced a candidate correction and it is awaiting a human decision.
        Entries the tutor itself rejected (status='rejected' at insert time)
        never appear here, mirroring how a tutor_rejected reply never becomes
        agent.pending_correction in the live single-correction flow either."""
        rows = self.connection.execute(
            """
            SELECT * FROM correction_queue
            WHERE status = 'pending'
            ORDER BY created_at ASC
            LIMIT ?
            """,
            (int(limit),),
        )
        return [self._row_to_dict(row) for row in rows]

    def set_status(
        self,
        entry_id: int,
        status: str,
        corrected_answer: str | None = None,
        new_words: list[str] | None = None,
    ) -> bool:
        if status not in VALID_STATUSES:
            raise ValueError(f"status must be one of {VALID_STATUSES}, got {status!r}")

        fields = ["status = ?"]
        values: list[Any] = [status]
        if corrected_answer is not None:
            fields.append("corrected_answer = ?")
            values.append(corrected_answer)
        if new_words is not None:
            fields.append("new_words = ?")
            values.append(json.dumps(new_words))
        values.append(entry_id)

        cursor = self.connection.execute(
            f"UPDATE correction_queue SET {', '.join(fields)} WHERE id = ?", values
        )
        self.connection.commit()
        return cursor.rowcount > 0

    def purge_rejected_before(self, cutoff: float) -> int:
        """Deletes 'rejected' entries with created_at < cutoff (unix time).

        Only ever touches status='rejected' rows -- 'pending' and 'approved'
        entries are never deleted by this method regardless of age, since a
        rejection can mean either a quality judgment (keep, it's signal) or
        an API-layer failure (e.g. a deprecated model or the reasoning-token
        bug swallowing the whole response) that never should have landed as
        a queue entry at all. Callers are responsible for picking a cutoff
        that only covers the known-bad period.
        """
        cursor = self.connection.execute(
            "DELETE FROM correction_queue WHERE status = 'rejected' AND created_at < ?",
            (cutoff,),
        )
        self.connection.commit()
        return cursor.rowcount

    def stats(self) -> dict[str, int]:
        counts = {status: 0 for status in VALID_STATUSES}
        rows = self.connection.execute(
            "SELECT status, COUNT(*) AS count FROM correction_queue GROUP BY status"
        )
        for row in rows:
            counts[row["status"]] = row["count"]
        return counts

    def _row_to_dict(self, row: sqlite3.Row) -> dict[str, Any]:
        return {
            "id": row["id"],
            "question": row["question"],
            "raw_answer": row["raw_answer"],
            "corrected_answer": row["corrected_answer"],
            "new_words": json.loads(row["new_words"]),
            "created_at": row["created_at"],
            "status": row["status"],
        }

    def close(self) -> None:
        self.connection.close()
